org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap-modularrouters
addon_name=BlueMap Modular Routers Add-on
addon_version=0.1.0-alpha.2
addon_group=io.github.jan-guenter
artifact_id=bluemap-modular-routers-addon
bluemap_version=5.22-feature.backport-5.23-stateless-java-web-server-46
accepted_jar_size=50021
accepted_jar_sha256=11073269fb60bb65a011aa987015264b73c1170bce93fc6677a6fe507ee22f45
accepted_sources_jar_size=28721
accepted_sources_jar_sha256=c328f9d896da758f42053b97298e43c166c4102ac50ff26083bec8e6b4f08276
accepted_pom_size=1376
accepted_pom_sha256=83bd1e0332250735d4d7dacf16f960027355a77e7e376649d4add4d611e68807
accepted_module_size=2873
accepted_module_sha256=c143fe978879bf91b07922c72250792ff3b20dc9374cdf117c9f619f6e1693a2
