org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap-modularrouters
addon_name=BlueMap Modular Routers Add-on
addon_version=0.1.0-alpha.1
addon_group=io.github.jan-guenter
artifact_id=bluemap-modular-routers-addon
bluemap_version=5.22-agent.backport-5.22-mc1.21.1-2
accepted_jar_size=46780
accepted_jar_sha256=c8e0c591169e12334abc85c3a917caffb5c82e4dd000acf92d0ff101b8f97a31
accepted_sources_jar_size=25493
accepted_sources_jar_sha256=7e48efaaae36d1350e0e9096200146f4659b2b919ca740032933696b6f718384
accepted_pom_size=1376
accepted_pom_sha256=2a381dbaa802d14f1ae71cdbf66b5be26b76d649b909e0fa161655e3ee637ab3
accepted_module_size=2873
accepted_module_sha256=ae7988b2a033583b0b79515e1c8bea527ae6ee53d573c969526bf200768a245a
