org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap-modularrouters
addon_name=BlueMap Modular Routers Add-on
addon_version=0.1.0-alpha.2
addon_group=io.github.jan-guenter
artifact_id=bluemap-modular-routers-addon
bluemap_version=5.22-feature.backport-5.23-stateless-java-web-server-46
accepted_jar_size=53593
accepted_jar_sha256=160a3fc276057e634b5c1c2dad7641028c7be811a5a7262d6da53c3936b8dfc2
accepted_sources_jar_size=30100
accepted_sources_jar_sha256=4f0775396de8c9efaad67ccc92842cb304d03f6fde51875afb2bc5576dd7bd42
accepted_pom_size=1376
accepted_pom_sha256=83bd1e0332250735d4d7dacf16f960027355a77e7e376649d4add4d611e68807
accepted_module_size=2873
accepted_module_sha256=a235e86a49c5889fa2c406f3fd330200f5d38a0ffead25356cba84318cd887bc
