# Generated by gallery/generate.py; do not edit.
scoreboard objectives add mr_gallery dummy
scoreboard players add #builds mr_gallery 1
function modularrouters_gallery:clear
forceload add 160 160 191 175
fill 160 99 160 191 99 175 minecraft:stone
# A1 stock router
setblock 164 100 164 modularrouters:modular_router[facing=north,active=false,can_emit=false]
# A2 oak-log router
setblock 170 100 164 modularrouters:modular_router[facing=north,active=false,can_emit=false]
data merge block 170 100 164 {Upgrades:{Size:5,Items:[{Slot:0,id:"modularrouters:camouflage_upgrade",count:1,components:{"modularrouters:camouflage":{Name:"minecraft:oak_log",Properties:{axis:"x"}}}}]}}
# A3 glass template frame
setblock 176 100 164 modularrouters:template_frame
data merge block 176 100 164 {CamouflageName:{Name:"minecraft:glass"},Mimic:0b}
# A4 stair template frame
setblock 182 100 164 modularrouters:template_frame
data merge block 182 100 164 {CamouflageName:{Name:"minecraft:deepslate_brick_stairs",Properties:{facing:"east",half:"top",shape:"straight",waterlogged:"false"}},Mimic:0b}
function modularrouters_gallery:verify_immediate
schedule function modularrouters_gallery:verify_20t 20t replace
schedule function modularrouters_gallery:verify_100t 100t replace
