# Generated by gallery/generate.py; do not edit.
function modularrouters_gallery:verify
scoreboard players operation #100t_failures mr_gallery = #failures mr_gallery
scoreboard players operation #100t_checked mr_gallery = #checked mr_gallery
tellraw @a [{"text":"Modular Routers gallery 100t: "},{"score":{"name":"#100t_checked","objective":"mr_gallery"}},{"text":" checks, "},{"score":{"name":"#100t_failures","objective":"mr_gallery"}},{"text":" failures"}]
