# Generated by gallery/generate.py; do not edit.
function modularrouters_gallery:verify
scoreboard players operation #20t_failures mr_gallery = #failures mr_gallery
scoreboard players operation #20t_checked mr_gallery = #checked mr_gallery
