# Generated by gallery/generate.py; do not edit.
scoreboard players set #failures mr_gallery 0
scoreboard players set #checked mr_gallery 0
# A1 stock router
execute unless block 164 100 164 modularrouters:modular_router[facing=north,active=false,can_emit=false] run scoreboard players add #failures mr_gallery 1
scoreboard players add #checked mr_gallery 1
# A2 oak-log router
execute unless block 170 100 164 modularrouters:modular_router[facing=north,active=false,can_emit=false] run scoreboard players add #failures mr_gallery 1
scoreboard players add #checked mr_gallery 1
execute unless data block 170 100 164 {Upgrades:{Size:5,Items:[{Slot:0,id:"modularrouters:camouflage_upgrade",count:1,components:{"modularrouters:camouflage":{Name:"minecraft:oak_log",Properties:{axis:"x"}}}}]}} run scoreboard players add #failures mr_gallery 1
scoreboard players add #checked mr_gallery 1
# A3 glass template frame
execute unless block 176 100 164 modularrouters:template_frame run scoreboard players add #failures mr_gallery 1
scoreboard players add #checked mr_gallery 1
execute unless data block 176 100 164 {CamouflageName:{Name:"minecraft:glass"},Mimic:0b} run scoreboard players add #failures mr_gallery 1
scoreboard players add #checked mr_gallery 1
# A4 stair template frame
execute unless block 182 100 164 modularrouters:template_frame run scoreboard players add #failures mr_gallery 1
scoreboard players add #checked mr_gallery 1
execute unless data block 182 100 164 {CamouflageName:{Name:"minecraft:deepslate_brick_stairs",Properties:{facing:"east",half:"top",shape:"straight",waterlogged:"false"}},Mimic:0b} run scoreboard players add #failures mr_gallery 1
scoreboard players add #checked mr_gallery 1
execute unless score #builds mr_gallery matches 1 run scoreboard players add #failures mr_gallery 1
scoreboard players add #checked mr_gallery 1
