# Generated by gallery/generate.py; do not edit.
function modularrouters_gallery:verify
scoreboard players operation #immediate_failures mr_gallery = #failures mr_gallery
scoreboard players operation #immediate_checked mr_gallery = #checked mr_gallery
tellraw @a [{"text":"Modular Routers gallery immediate: "},{"score":{"name":"#immediate_checked","objective":"mr_gallery"}},{"text":" checks, "},{"score":{"name":"#immediate_failures","objective":"mr_gallery"}},{"text":" failures"}]
